# Generated by Django 5.1.2 on 2024-10-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.TextField()),
                ('firstName', models.TextField()),
                ('patronymic', models.TextField()),
                ('dateBirth', models.TextField()),
                ('number', models.TextField()),
            ],
        ),
    ]
