# Generated by Django 5.1.2 on 2024-10-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_rename_patients_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='dateBirth',
            field=models.TextField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='firstName',
            field=models.TextField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastName',
            field=models.TextField(verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='number',
            field=models.TextField(verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patronymic',
            field=models.TextField(verbose_name='Отчество'),
        ),
    ]
