# Generated by Django 5.1.2 on 2024-10-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_alter_patient_options_alter_patient_datebirth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
    ]
