# Generated by Django 5.1.2 on 2024-10-28 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_alter_patient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
    ]
