# Generated by Django 5.1.2 on 2024-10-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0006_medicine_patient_medicine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': 'Лекарство', 'verbose_name_plural': 'Лекарства'},
        ),
    ]
