# Generated by Django 5.1.2 on 2024-10-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0007_alter_medicine_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='ReleaseForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.TextField(verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Форма выпуска',
                'verbose_name_plural': 'Формы выпуска',
            },
        ),
        migrations.CreateModel(
            name='TherapeuticAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='действие')),
            ],
            options={
                'verbose_name': 'Терапевтическое действие',
                'verbose_name_plural': 'Терапевтическое действия',
            },
        ),
    ]
