# Generated by Django 5.1.2 on 2024-10-28 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0008_doctor_releaseform_therapeuticaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapeuticaction',
            options={'verbose_name': 'Терапевтическое действие', 'verbose_name_plural': 'Терапевтические действия'},
        ),
        migrations.AddField(
            model_name='medicine',
            name='releaseForm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicines.releaseform'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='therapeuticAction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicines.therapeuticaction'),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicines.doctor'),
        ),
    ]
