# Generated by Django 5.1.2 on 2024-11-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0009_alter_therapeuticaction_options_medicine_releaseform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='picture',
            field=models.ImageField(null=True, upload_to='patients', verbose_name='Изображение'),
        ),
    ]
